config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
    namespace :admin do
      resources :users, except: %(create new edit) do
        get "banned", on: :collection
        put "unbanned", on: :member
        get "search", on: :collection
        get "modal_role", on: :member
      end
      resources :timesheets, except: %(create new edit)
    end
  end
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post "sign_up", :to => "registration#create"
        post "sign_in", :to => "session#create"
        delete "sign_out", :to => "session#destroy"
        get "show", :to => "user#show"
        post "update", :to => "user#update"
        post "change_password", :to => "user#change_password"
        resources :timesheets, only: %i(show create) do
            get "list", on: :collection
        end
        get "timesheet-details/:id", :to => "timesheets#detail"
        delete "timesheets/:id", :to => "timesheets#soft_delete"
      end
    end
  end
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
  acts_as_paranoid
  before_create :create_check_in
  belongs_to :user
  belongs_to :shift
  has_many :timesheet_details, -> { with_deleted }
  has_one :contact, through: :user
  # validates_associated :timesheet_details
  delegate :email, to: :user, prefix: true
  delegate :name, to: :shift, prefix: true, allow_nil: true
  delegate :name, to: :contact, prefix: true, allow_nil: true

  scope :with_checkin_today, ->(id) {
    where(check_in: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
    .where(user_id: id)}

  enum status: [:notcheckout, :checkout], _prefix: true

  private
  def create_check_in
    self.check_in = Time.current
    self.check_out = Time.current
    self.hours = 0
    self.status = false
  end
end

app/controllers/admin/timesheets_controller.rb
class Admin::TimesheetsController < Admin::AdminsController
  before_action :load_timesheet, only: :destroy
  authorize_resource

  def index
    @stt = 0
    @timesheets = Timesheet.page(params[:page]).order('check_in DESC').per(8)
  end

  def destroy
    respond_to do | format |
      begin
        if @timesheet.destroy
          flash[:success] = "Deleted!"
        else
          flash[:error] = "Error!!"
        end
      rescue => e
        flash[:error] = "Error!!"
      end
      format.js
    end
  end

  private
  def load_timesheet
    @timesheet = Timesheet.with_deleted.find_by(id: params[:id])
    return if @timesheet
  end
end

app/controllers/api/v1/timesheets_controller.rb
class Api::V1::TimesheetsController < Api::V1::AuthController
  before_action :load_timesheet, only: %i(show soft_delete)
  before_action :load_timesheet_details, only: :details
  before_action :check_exist_timesheet, :ensure_params_exist, only: :create
  # respond_to :json
  load_and_authorize_resource

  def soft_delete
    if @timesheet.destroy
      render json: {message: "Deleted"}, status: 200
    else
      render json: {message: "Error"}, status: 401
    end
  end

  def show
    render json: {message: "ok", timesheet: @timesheet}, status: 200
  end

  def detail
    render json: {message: "ok", timesheet: @timesheet}, status: 200
  end

  def list
    ts = @current_user.timesheets.order('check_in DESC').page(params[:page]).per(5)
    render json: {message: "ok", timesheet: ts}, status: 200
  end

  def create
    if @timesheet
      ActiveRecord::Base.transaction do
        ts = @timesheet
        ts.status_checkout!
        ts.hours = work_hours(ts.check_in)
        ts.timesheet_details.build timesheet_detail_params
        ts.save!
        render json: {message: "Updated", timesheet: ts}, status: 201
      end
    else
      ActiveRecord::Base.transaction do
        ts = @current_user.timesheets.create! timesheet_params
        ts.timesheet_details.build timesheet_detail_params
        ts.save!
        render json: {message: "Created", timesheet: ts}, status: 201
      end
    end
  rescue ActiveRecord::RecordInvalid => invalid
    render json: { message: invalid.record.errors.full_messages }, status: 422
  end

  private
  def timesheet_params
    params.require(:timesheet)
          .permit(:location, :late, :note, :user_id, :shift_id)
  end

  def timesheet_detail_params
    params.require(:timesheet_detail)
          .permit(:latitude, :longitude, :distance, :accuracy,
                  :ip_address, :confidence, :image, :note)
  end

  def ensure_params_exist
    return unless params[:timesheet_detail].blank?
    render json: {message: "Missing params"}, status: 422
  end

  def load_timesheet
    @timesheet = Timesheet.find_by(id: params[:id])
    return if @timesheet

    render json: {message: "Not found!"}, status: 200
  end

  def load_timesheet_details
    @timesheet = Timesheet.includes(:user, :timesheet_details)
                          .find_by(id: params[:id])
                          .as_json(include: %i(user timesheet_details))
    return if @timesheet
    render json: {message: "Not found!"}, status: 200
  end

  def check_exist_timesheet
    @timesheet = Timesheet.with_checkin_today(@current_user.id).first
  end

  def work_hours check_in
    TimeDifference.between(check_in, Time.current).in_hours
  end
end

app/helpers/admin/timesheets_helper.rb
module Admin::TimesheetsHelper
end

app/helpers/api/v1/timesheets_helper.rb
module Api::V1::TimesheetsHelper
end

app/views/admin/timesheets/_timesheet.html.erb
<tr id="selectTimesheet<%= timesheet.id %>">
  <th scope="row"><%= @stt+=1 %></th>
  <td><%= timesheet.contact_name %></td>
  <td><%= timesheet.user_email %></td>
  <td><%= timesheet.check_in %></td>
  <td><%= timesheet.check_out %></td>
  <td><%= timesheet.shift_name %></td>
  <td>
    <%= link_to admin_timesheet_path(timesheet), method: :delete, remote: true, data: { confirm: t("you_sure") } do %>
      <button type="button" class="btn btn-danger btn-sm">
        <span class="material-icons">delete_forever</span>
      </button>
    <% end %>
  </td>
</tr>

app/views/admin/timesheets/destroy.js.erb
var select<%= @timesheet.id %> = document.querySelector("#selectTimesheet<%= @timesheet.id %>");
<% flash.each do |type, message| %>
     <% type = 'success' if type == 'notice' %>
     <% type = 'error'   if type == 'alert' %>
     <% type = 'error'   if type == 'danger' %>
     <% if type != 'error'%>
       select<%= @timesheet.id %>.remove();
     <% end %>
     toastr.<%= type %>("<%= message %>");
<% end %>

app/views/admin/timesheets/index.html.erb
<div class="page-info">
  <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#"><%= t "admin.users.dashboard" %></a></li>
        <li class="breadcrumb-item active" aria-current="page"><%= t "timesheets.timesheet" %></li>
      </ol>
  </nav>
</div>
<div class="main-wrapper">
  <div class="row stats-row">
    <div class="col-xl">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Table Head Options</h5>
          <!-- <p>
            Use the modifier classes <code>.thead-light</code> or
            <code>.thead-dark</code> to make <code>&lt;thead&gt;</code>s appear
            light or dark gray.
          </p> -->
          <table class="table" id="timesheets-table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col"><%= t "timesheets.name" %></th>
                <th scope="col"><%= t "timesheets.email" %></th>
                <th scope="col"><%= t "timesheets.checkin" %></th>
                <th scope="col"><%= t "timesheets.checkout" %></th>
                <th scope="col"><%= t "timesheets.shift" %></th>
                <th scope="col"><%= t "edit" %>/<%= t "delete" %></th>
              </tr>
            </thead>
            <tbody id="timesheets">
              <%= render @timesheets %>
            </tbody>
          </table>
          <div id="search-results"></div>
          <div id="paginator">
            <%= paginate @timesheets, remote: true %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="modal-timesheets"></div>

app/views/admin/timesheets/index.js.erb
$("#timesheets").html("<%= j render(@timesheets) %>");
$("#paginator").html("<%= j paginate(@timesheets, remote: true) %>");