config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
    namespace :admin do
      resources :users, except: %(create new edit) do
        get "banned", on: :collection
        put "unbanned", on: :member
        get "search", on: :collection
        get "modal_role", on: :member
      end
      resources :timesheets, except: %(create new edit)
    end
  end
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post "sign_up", :to => "registration#create"
        post "sign_in", :to => "session#create"
        delete "sign_out", :to => "session#destroy"
        get "show", :to => "user#show"
        post "update", :to => "user#update"
        post "change_password", :to => "user#change_password"
        resources :timesheets, only: %i(show create) do
            get "list", on: :collection
        end
        get "timesheet-details/:id", :to => "timesheets#detail"
        delete "timesheets/:id", :to => "timesheets#soft_delete"
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  has_one :contact, -> { with_deleted }, dependent: :destroy
  has_many :timesheets
  has_one_attached :avatar
  belongs_to :role
  accepts_nested_attributes_for :contact, reject_if: :all_blank, update_only: true
  acts_as_token_authenticatable
  delegate :name, :phone, :address, :gender,
  to: :contact, prefix: true, allow_nil: true
  delegate :slug, to: :role, prefix: true, allow_nil: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :omniauthable, omniauth_providers: [:google_oauth2]
  scope :with_contact_role, -> { includes(:contact, :role) }
  scope :with_email, -> (email){ with_deleted.where email: email }

  def self.from_omniauth(access_token)
    user = User.with_email(access_token.info.email).first
    ActiveRecord::Base.transaction do
      unless user
        role = Role.user_role.first
        user = User.create(email: access_token.info.email,
          password: Devise.friendly_token[0,20],
          role_id: role.id)
        user.uid = access_token.uid
        user.image = access_token.info.image
        user.provider = access_token.provider
        user.build_contact(name: access_token.info.name)
        UserMailer.welcome(user).deliver if ENV["MAIL_WELCOME"]
      else
        unless user.contact
          user.build_contact
          user.contact.update(name: access_token.info.name)
        end
      end
      user.save!
    end
    return user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminsController
  before_action :load_user, only: %i(show modal_role unbanned destroy update)
  before_action :set_search, only: %i(index banned)
  authorize_resource

  def index
    @users = User.with_contact_role.page(params[:page]).order('email ASC').per(8)
  end

  def show; end

  def modal_role
    @roles = Role.all
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      begin
        slug_role = params["radioRole"]
        if(Role.slugs.include?(slug_role) && current_user.role.admin_role?)
          role = Role.send(slug_role).first
          @user.update_attribute :role_id, role.id
        end
        flash[:success] = "Success!"
      rescue => e
        flash[:error] = "Error!!"
      end
      format.js
    end
  end

  def search
    @q = User.with_deleted.ransack(params[:q])
    @users = @q.result.with_contact_role.page(params[:page]).per(8)
    @stt = 0
    respond_to do |format|
      format.js
    end
  end

  def banned
    @users = User.only_deleted.with_contact_role.order('email ASC').page(params[:page]).per(8)
    render "index"
  end

  def unbanned
    respond_to do | format |
      begin
        if @user.restore
          flash[:success] = "Restore Success!"
        else
          flash[:error] = "Error!!"
        end
      rescue => e
        flash[:error] = "Error!!"
      end
      format.js {
        render  :partial => "remove"
      }
    end
  end

  def destroy
    respond_to do | format |
      begin
        if @user.destroy
          flash[:success] = "Banned!"
        else
          flash[:error] = "Error!!"
        end
      rescue => e
        flash[:error] = "Error!!"
      end
      # format.html
      format.js {
        render  :partial => "remove"
      }
    end
    # redirect_back(fallback_location: admin_user_path)
  end

  private
  def load_user
    @user = User.with_deleted.includes(:role).find_by(id: params[:id])
    return if @user
  end

  def set_search
    @stt = 0
    @q = User.ransack(params[:q])
  end
end

app/controllers/api/v1/user_controller.rb
class Api::V1::UserController < Api::V1::AuthController
  before_action :ensure_params_exist, except: :show

  def show
    user = User.includes(:contact).find_by(id: @current_user.id).as_json(include: :contact)
    render json: {message: "Infor user", user: user}, status: 200
  end

  def update
    if @current_user.update(user_params)
      render json: {message: "Completed", user: @current_user.contact}, status: 200
    else
      warden.custom_failure!
      render json: {message: @current_user.contact.errors.messages}, status: 200
    end
  end

  def change_password
    if @current_user.valid_password? user_params[:current_password]
      @current_user.password = (user_params[:password])
      if @current_user.save
        render json: {message: "Changed password completed", user: @current_user}, status: 200
      else
        warden.custom_failure!
        render json: {message: @current_user.errors.messages}, status: 200
      end
    else
      render json: {message: "Password incorect"}, status: 200
    end
  end

  private
  def user_params
    params.require(:user).permit(:current_password, :password, contact_attributes: [:name, :phone, :gender, :address])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Google"
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  invisible_captcha only: :create

  def new
    build_resource {}
    self.resource.contact = Contact.new
    respond_with self.resource
  end

  def configure_sign_up_params
    role = Role.user_role.first
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(
      :email, :password, :password_confirmation,
      contact_attributes: [:name, :phone, :gender, :address]
    ).reverse_merge({ role_id: role.id })}
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit :password, :password_confirmation}
  end


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]

  # GET /users
  def index
    @users = User.all

    render json: @users
  end

  # GET /users/1
  def show
    render json: @user
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      render json: @user, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/api/v1/user_helper.rb
module Api::V1::UserHelper
end

app/views/admin/users/_modal_role.html.erb
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="roleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class=""><%= t "roles.change_role" %>: <%= @user.email %> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for [:admin, @user], remote: true do |f| %>
        <div class="modal-body">
          <div>
            <% @roles.each do |role| %>
              <div class="form-check">
                <input class="form-check-input" name="radioRole" type="radio" id="flexRadio<%= role.id %>" value="<%= role.slug %>" <%= "checked" if @user.role == role %>>
                <label class="form-check-label"><%= t("roles.#{role.slug}") %></label>
              </div>
            <% end %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t "close" %></button>
          <%= f.submit t("save"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/_remove.js.erb
let select<%= @user.id %> = document.querySelector("#selectUser" + <%= @user.id %>);
<% flash.each do |type, message| %>
     <% type = 'success' if type == 'notice' %>
     <% type = 'error'   if type == 'alert' %>
     <% type = 'error'   if type == 'danger' %>
     <% if type != 'error'%>
       select<%= @user.id %>.remove();
     <% end %>
     toastr.<%= type %>("<%= message %>");
<% end %>

app/views/admin/users/_results.html.erb
<table class="table" id="users-table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col">Role</th>
      <th scope="col">Ban/Unban</th>
    </tr>
  </thead>
  <tbody id="users">
    <%= render @users %>
  </tbody>
</table>

app/views/admin/users/_search-results.js.erb
$("#users-table").hide();
$("#search-results").html("<%= escape_javascript(render partial: 'results') %>");
$("#paginator").html("<%= j paginate(@users, remote: true) %>");

app/views/admin/users/_user.html.erb
<tr id="selectUser<%= user.id %>">
  <th scope="row"><%= @stt+=1 %></th>
  <td><%= user.email %></td>
  <td><%= user.contact_name %></td>
  <td><%= user.contact_phone %></td>
  <td><%= user.contact_address %></td>
  <td>
    <%= button_to t("roles.#{user.role_slug}"), modal_role_admin_user_path(user), method: :get,
        remote: true, id: "User#{user.id}", class: "btn btn-info btn-xs btn-block" %>
  </td>
  <td>
    <% if user.deleted_at? %>
      <%= link_to unbanned_admin_user_path(user), method: :put, remote: true, data: { confirm: t("you_sure") } do %>
        <button type="button" class="btn btn-danger btn-sm">
          <span class="material-icons-outlined">undo</span>
        </button>
      <% end %>
    <% else %>
      <%= link_to admin_user_path(user), method: :delete, remote: true, data: { confirm: t("you_sure") } do %>
        <button type="button" class="btn btn-danger btn-sm">
          <span class="material-icons-outlined">remove_circle</span>
        </button>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/users/index.html.erb
<% provide :title, "Manager Accounts" %>
<% content_for :navbarsearch do %>
  <div class="navbar-search">
    <%= search_form_for @q, url: search_admin_users_path, remote: true do |f| %>
      <div class="form-group">
        <%= f.search_field :contact_name_or_contact_phone_or_email_cont, :id => 'nav-search', placeholder: 'Search' %>
        <!-- <%= f.submit "save creature", class: "btn btn-default"%> -->
      </div>
    <% end %>
  </div>
<% end %>

<div class="page-info">
  <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#"><%= t "admin.users.dashboard" %></a></li>
          <li class="breadcrumb-item active" aria-current="page"><%= t "users.account" %></li>
      </ol>
  </nav>
  <div class="page-options">
      <%= link_to t("users.banned"), banned_admin_users_path, class: "btn btn-secondary" %>
      <%= link_to t("users.active"), admin_users_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="main-wrapper">
  <div class="row stats-row">
    <div class="col-xl">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Table Head Options</h5>
          <!-- <p>
            Use the modifier classes <code>.thead-light</code> or
            <code>.thead-dark</code> to make <code>&lt;thead&gt;</code>s appear
            light or dark gray.
          </p> -->
          <table class="table" id="users-table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col"><%= t "users.email" %></th>
                <th scope="col"><%= t "users.name" %></th>
                <th scope="col"><%= t "users.phone" %></th>
                <th scope="col"><%= t "users.address" %></th>
                <th scope="col"><%= t "users.role" %></th>
                <th scope="col"><%= t "users.ban" %>/<%= t "users.unban" %></th>
              </tr>
            </thead>
            <tbody id="users">
              <%= render @users %>
            </tbody>
          </table>
          <div id="search-results"></div>
          <div id="paginator">
            <%= paginate @users, remote: true %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="modal-role"></div>

app/views/admin/users/index.js.erb
$("#users").html("<%= j render(@users) %>");
$("#paginator").html("<%= j paginate(@users, remote: true) %>");

app/views/admin/users/modal_role.js.erb
$('#modal-role').html("<%= j render 'modal_role' %>");
$('#modal').modal('show');

app/views/admin/users/search.js.erb
$("#users-table").hide();
$("#search-results").html("<%= escape_javascript(render partial: 'results') %>");
$("#paginator").html("<%= j paginate(@users, remote: true) %>");

app/views/admin/users/update.js.erb
document.getElementById("User<%= @user.id %>").value = "<%= t "roles.#{@user.role_slug}" %>";
<% flash.each do |type, message| %>
     <% type = 'success' if type == 'notice' %>
     <% type = 'error'   if type == 'alert' %>
     <% type = 'error'   if type == 'danger' %>
     <% if type == 'success'%>
        $('#modal').modal('hide');
     <% end %>
     toastr.<%= type %>("<%= message %>");
<% end %>