config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
    namespace :admin do
      resources :users, except: %(create new edit) do
        get "banned", on: :collection
        put "unbanned", on: :member
        get "search", on: :collection
        get "modal_role", on: :member
      end
      resources :timesheets, except: %(create new edit)
    end
  end
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post "sign_up", :to => "registration#create"
        post "sign_in", :to => "session#create"
        delete "sign_out", :to => "session#destroy"
        get "show", :to => "user#show"
        post "update", :to => "user#update"
        post "change_password", :to => "user#change_password"
        resources :timesheets, only: %i(show create) do
            get "list", on: :collection
        end
        get "timesheet-details/:id", :to => "timesheets#detail"
        delete "timesheets/:id", :to => "timesheets#soft_delete"
      end
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><%= full_title yield :title %></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Dashboard">
        <meta name="keywords" content="admin,dashboard">
        <meta name="author" content="Vanquy">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <!-- Styles -->
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/css/toastr.css" rel="stylesheet">

        <!-- Theme Styles -->
        <link href="/assets/css/connect.min.css" rel="stylesheet">
        <link href="/assets/css/admin3.css" rel="stylesheet">
        <script src="/assets/js/jquery-3.4.1.min.js"></script>
        <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    </head>
    <body>
        <!-- <div class='loader'>
            <div class='spinner-grow text-primary' role='status'>
                <span class='sr-only'>Loading...</span>
            </div>
        </div> -->
        <div class="connect-container align-content-stretch d-flex flex-wrap">
            <div class="page-sidebar">
                <div class="logo-box"><a href="#" class="logo-text">Connect</a><a href="#" id="sidebar-close"><i class="material-icons">close</i></a> <a href="#" id="sidebar-state"><i class="material-icons">adjust</i><i class="material-icons compact-sidebar-icon">panorama_fish_eye</i></a></div>
                <div class="page-sidebar-inner slimscroll">
                    <ul class="accordion-menu">
                        <li class="sidebar-title">
                            Apps
                        </li>
                        <li>
                            <!-- class="active-page" class="active" -->
                            <a href=""><i class="material-icons-outlined">dashboard</i>Dashboard</a>
                        </li>
                        <li>
                            <a href=""><i class="material-icons-outlined">inbox</i>Mailbox</a>
                        </li>
                        <li>
                            <a href=""><i class="material-icons-outlined">account_circle</i>Profile</a>
                        </li>
                        <li>
                            <%= link_to admin_timesheets_path, method: :get do %>
                                <i class="material-icons-outlined">table_view</i><%= t "timesheets.timesheet" %>
                            <% end %>
                        </li>
                        <li>
                            <a href=""><i class="material-icons">done</i>Todo</a>
                        </li>
                        <li class="sidebar-title">
                            UI Elements
                        </li>

                        <li>
                            <a href=""><i class="material-icons">card_giftcard</i>Extended<i class="material-icons has-sub-menu">add</i></a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="extended-select2.html">Select2</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <%= link_to admin_users_path, method: :get do %>
                                <i class="material-icons">account_box</i><%= t "users.user" %>
                            <% end %>
                            <!-- <a href="charts.html"><i class="material-icons">bar_chart</i>Charts</a> -->
                        </li>
                        <li>
                            <a href=""><i class="material-icons">input</i>Forms</a>
                        </li>
                        <li class="sidebar-title">
                            Other
                        </li>
                        <li>
                            <a href="#"><i class="material-icons">access_time</i>Change Log</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="page-container">
                <div class="page-header">
                    <nav class="navbar navbar-expand">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <ul class="navbar-nav">
                            <li class="nav-item small-screens-sidebar-link">
                                <a href="#" class="nav-link"><i class="material-icons-outlined">menu</i></a>
                            </li>
                            <li class="nav-item nav-profile dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <%= image_tag(current_user.image ||= "/assets/images/profile-image.png", alt: "Profile image") %>
                                    <span><%= current_user.contact_name %></span><i class="material-icons dropdown-icon">keyboard_arrow_down</i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Settings &amp Privacy</a>
                                    <div class="dropdown-divider"></div>
                                    <%= link_to t("vietnamese"), url_for(locale: :vi), class: "dropdown-item" %>
                                    <%= link_to t("english"), url_for(locale: :en), class: "dropdown-item" %>
                                    <div class="dropdown-divider"></div>
                                    <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link"><i class="material-icons-outlined">notifications</i></a>
                            </li>
                        </ul>
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a href="#" class="nav-link">Projects</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">Tasks</a>
                                </li>
                            </ul>
                        </div>
                        <%= yield :navbarsearch %>
                    </nav>
                </div>
                <div class="page-content">
                    <%= yield %>
                </div>
            </div>
        </div>

        <!-- Javascripts -->
        <script src="/assets/js/popper.min.js"></script>
        <script src="/assets/js/bootstrap.min.js"></script>
        <script src="/assets/js/jquery.slimscroll.min.js"></script>
        <script src="/assets/js/jquery.sparkline.min.js"></script>
        <script src="/assets/js/apexcharts.min.js"></script>
        <script src="/assets/js/jquery.blockUI.js"></script>
        <script src="/assets/js/jquery.flot.min.js"></script>
        <script src="/assets/js/jquery.flot.time.min.js"></script>
        <script src="/assets/js/jquery.flot.symbol.min.js"></script>
        <script src="/assets/js/jquery.flot.resize.min.js"></script>
        <script src="/assets/js/jquery.flot.tooltip.min.js"></script>
        <script src="/assets/js/connect.min.js"></script>
        <script src="/assets/js/dashboard.js"></script>
        <script src="/assets/js/toastr.js"></script>
        <%= custom_bootstrap_flash %>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>